apiVersion: v1
kind: Namespace
metadata:
  name: pnp-opsera-dan-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnp-opsera-dan-deployment
  namespace: pnp-opsera-dan-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:4f0fa7fae17646b80e94c2b24062459da2e8afbb

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pnp-opsera-dan-label
  name: pnp-opsera-dan-service
  namespace: pnp-opsera-dan-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---